"""Regression tests for `synthesize_fixtures_emission_from_existing`.

Background — the bug this pins:
    The deterministic writer at `.claude/melleafy/writers/fixtures_writer.py`
    renders the `fixtures/` subpackage from
    `<package>/intermediate/fixtures_emission.json`. When the LLM ran the
    full pipeline (and the LLM's own smoke check passed against working
    fixture .py files) but forgot to emit `fixtures_emission.json`, the
    wrapper's wipe-then-render contract reported ``missing-emission`` AFTER
    already wiping the LLM-written fixture files — destroying the LLM's
    work and tripping the ``fixtures-loader-contract`` lint on the empty
    ``fixtures/`` directory. The sentry-find-bugs overnight run is the
    documented instance of this failure.

    The fix reverse-engineers `fixtures_emission.json` from the surviving
    fixture .py files BEFORE the writer's wipe-then-render runs. The
    writer then re-renders the same fixtures byte-identically (because the
    synthesized IR captured what was already there), the lint passes, and
    the package's IR + on-disk state stays self-consistent.

    The sibling synthesizer for `config_emission.json` lives next to this
    one in `writer_renderer.py` (Track 1 #4).
"""
from __future__ import annotations

import json
import logging
import textwrap
from pathlib import Path

import pytest

from mellea_skills_compiler.compile.writer_renderer import (
    synthesize_fixtures_emission_from_existing,
)
from mellea_skills_compiler.toolkit.logging import configure_logger


def _write_fixture_file(
    fixtures_dir: Path,
    *,
    fid: str,
    description: str,
    inputs: dict,
) -> Path:
    """Helper: render one auto-generated-style fixture .py file.

    Mirrors the shape produced by `.claude/melleafy/writers/fixtures_writer.py`
    so the synthesizer's AST extraction is exercised on realistic inputs.
    """
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    inputs_repr = ", ".join(f"{k!r}: {v!r}" for k, v in inputs.items())
    body = textwrap.dedent(
        f'''\
        """Auto-generated by melleafy from fixtures_emission JSON. Fixture id="{fid}"."""


        def make_{fid}():
            inputs = {{{inputs_repr}}}
            return inputs, {fid!r}, {description!r}
        '''
    )
    path = fixtures_dir / f"{fid}.py"
    path.write_text(body)
    return path


def _write_init_file(fixtures_dir: Path, fids: list[str], coverage_doc: str | None = None) -> Path:
    """Helper: render a fixtures/__init__.py file referencing the given fids."""
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    if coverage_doc is not None:
        lines.append('"""')
        lines.append(coverage_doc)
        lines.append('"""')
    else:
        lines.append('"""Auto-generated by melleafy from fixtures_emission JSON."""')
    lines.append("from typing import Callable")
    lines.append("")
    for fid in fids:
        lines.append(f"from .{fid} import make_{fid}")
    lines.append("")
    lines.append("ALL_FIXTURES: list[Callable] = [")
    for fid in fids:
        lines.append(f"    make_{fid},")
    lines.append("]")
    init_path = fixtures_dir / "__init__.py"
    init_path.write_text("\n".join(lines) + "\n")
    return init_path


class TestSynthesizeFixturesEmissionFromExisting:
    """Pin the fallback semantics for the fixtures_emission.json synthesizer."""

    def test_synthesizes_when_missing_with_existing_fixtures(self, tmp_path: Path) -> None:
        """No IR on disk + one fixture .py → synthesise IR with that fixture."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="clean_text",
            description="Benign user query — no threat patterns",
            inputs={"input_text": "Hello world", "check_mode": "validate"},
        )

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is not None
        assert "fixtures" in result
        assert len(result["fixtures"]) == 1
        entry = result["fixtures"][0]
        assert entry["id"] == "clean_text"
        assert entry["description"] == "Benign user query — no threat patterns"
        assert entry["inputs"] == {"input_text": "Hello world", "check_mode": "validate"}

    def test_passthrough_when_present(self, tmp_path: Path) -> None:
        """Existing emission is returned verbatim and never overwritten."""
        package_dir = tmp_path / "demo_mellea"
        intermediate = package_dir / "intermediate"
        intermediate.mkdir(parents=True)
        existing = {
            "fixtures": [
                {
                    "id": "preserved",
                    "description": "Pre-existing emission — must survive synth",
                    "inputs": {"foo": "bar"},
                }
            ]
        }
        emission_path = intermediate / "fixtures_emission.json"
        emission_path.write_text(json.dumps(existing))
        original_text = emission_path.read_text()
        # Even if a totally different fixture file is on disk, the IR is the
        # source of truth when it exists.
        _write_fixture_file(
            package_dir / "fixtures",
            fid="something_else",
            description="Disk drift the synth must not pick up",
            inputs={"k": "v"},
        )

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result == existing
        assert emission_path.read_text() == original_text

    def test_returns_none_when_no_fixtures_dir(self, tmp_path: Path) -> None:
        """Neither IR nor fixtures/ on disk → return None."""
        package_dir = tmp_path / "demo_mellea"
        package_dir.mkdir()

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is None
        assert not (package_dir / "intermediate" / "fixtures_emission.json").exists()

    def test_returns_none_when_fixtures_dir_empty(self, tmp_path: Path) -> None:
        """`fixtures/__init__.py` only → nothing to reverse-engineer → None."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        fixtures_dir.mkdir(parents=True)
        (fixtures_dir / "__init__.py").write_text('"""empty fixtures dir"""\n')

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is None
        assert not (package_dir / "intermediate" / "fixtures_emission.json").exists()

    def test_handles_multiple_fixtures(self, tmp_path: Path) -> None:
        """3 fixture .py files → 3 entries in the synthesized IR."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="fixture_alpha",
            description="alpha description",
            inputs={"k": "alpha"},
        )
        _write_fixture_file(
            fixtures_dir,
            fid="fixture_beta",
            description="beta description",
            inputs={"k": "beta"},
        )
        _write_fixture_file(
            fixtures_dir,
            fid="fixture_gamma",
            description="gamma description",
            inputs={"k": "gamma"},
        )
        # Init file declares an explicit order — the synthesizer should
        # respect it rather than the lexicographic file-system order.
        _write_init_file(
            fixtures_dir, ["fixture_beta", "fixture_alpha", "fixture_gamma"]
        )

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is not None
        ids = [f["id"] for f in result["fixtures"]]
        assert ids == ["fixture_beta", "fixture_alpha", "fixture_gamma"]
        for entry in result["fixtures"]:
            assert entry["inputs"]["k"] == entry["id"].removeprefix("fixture_")

    def test_falls_back_to_import_for_non_literal_returns(self, tmp_path: Path) -> None:
        """Fixture that computes its inputs from runtime values triggers the
        import-based fallback rather than the literal AST path."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        fixtures_dir.mkdir(parents=True)
        # The inputs come from a helper function — `ast.literal_eval` cannot
        # resolve this, so the synthesizer must import the module.
        (fixtures_dir / "computed_inputs.py").write_text(
            textwrap.dedent(
                '''\
                """Hand-edited fixture — computes inputs at runtime."""


                def _build_inputs():
                    parts = ["alpha", "beta", "gamma"]
                    return {"diff": "::".join(parts)}


                def make_computed_inputs():
                    inputs = _build_inputs()
                    return inputs, "computed_inputs", "computed via helper"
                '''
            )
        )

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is not None
        assert len(result["fixtures"]) == 1
        entry = result["fixtures"][0]
        assert entry["id"] == "computed_inputs"
        assert entry["description"] == "computed via helper"
        assert entry["inputs"] == {"diff": "alpha::beta::gamma"}

    def test_synthesized_conforms_to_schema(self, tmp_path: Path) -> None:
        """Synthesized JSON must validate against fixtures_emission.schema.json.

        The schema requires 5-8 fixtures, so we emit 5 to clear the floor.
        """
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        for i in range(5):
            _write_fixture_file(
                fixtures_dir,
                fid=f"fixture_{i:02d}",
                description=f"Fixture number {i}",
                inputs={"diff": f"diff body {i}", "mode": "validate"},
            )

        result = synthesize_fixtures_emission_from_existing(package_dir)
        assert result is not None

        # Resolve schema using the same path the writer-renderer uses.
        import mellea_skills_compiler
        from mellea_skills_compiler.compile.mellea_skills import (
            _resolve_writers_repo_root,
        )

        compiler_pkg_dir = Path(mellea_skills_compiler.__file__).resolve().parent
        repo_root = _resolve_writers_repo_root(compiler_pkg_dir)
        schema_path = (
            repo_root / ".claude" / "schemas" / "fixtures_emission.schema.json"
        )
        schema = json.loads(schema_path.read_text())

        import jsonschema

        jsonschema.Draft202012Validator(schema).validate(result)

    def test_end_to_end_preserves_fixtures_through_writer(
        self, tmp_path: Path
    ) -> None:
        """Full round-trip: package has fixtures + no IR → synthesize → run
        writer → confirm `fixtures/__init__.py` plus per-fixture files
        all exist after the wipe-then-render.
        """
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="alpha",
            description="alpha desc",
            inputs={"x": 1},
        )
        _write_fixture_file(
            fixtures_dir,
            fid="bravo",
            description="bravo desc",
            inputs={"x": 2},
        )

        # Step 1: synthesize the IR from the existing files.
        result = synthesize_fixtures_emission_from_existing(package_dir)
        assert result is not None

        # Step 2: invoke the deterministic writer on the synthesized IR.
        import importlib.util
        import mellea_skills_compiler
        from mellea_skills_compiler.compile.mellea_skills import (
            _resolve_writers_repo_root,
        )

        compiler_pkg_dir = Path(mellea_skills_compiler.__file__).resolve().parent
        repo_root = _resolve_writers_repo_root(compiler_pkg_dir)
        writer_path = (
            repo_root / ".claude" / "melleafy" / "writers" / "fixtures_writer.py"
        )
        spec = importlib.util.spec_from_file_location("fixtures_writer", writer_path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        # Wipe and rewrite — same flow the writer-renderer does.
        for child in fixtures_dir.iterdir():
            if child.is_file():
                child.unlink()
        written = module.write(result, fixtures_dir)

        # Step 3: confirm `__init__.py` and both fixture files re-emerged.
        assert (fixtures_dir / "__init__.py").is_file()
        assert (fixtures_dir / "alpha.py").is_file()
        assert (fixtures_dir / "bravo.py").is_file()
        assert {p.name for p in written} == {
            "__init__.py",
            "alpha.py",
            "bravo.py",
        }

    def test_round_trip_idempotent(self, tmp_path: Path) -> None:
        """Synthesizing twice produces identical IR — pinning idempotence."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="alpha",
            description="alpha desc",
            inputs={"input_text": "hello"},
        )
        _write_fixture_file(
            fixtures_dir,
            fid="bravo",
            description="bravo desc",
            inputs={"input_text": "world"},
        )

        first = synthesize_fixtures_emission_from_existing(package_dir)
        emission_path = package_dir / "intermediate" / "fixtures_emission.json"
        assert emission_path.exists()
        first_text = emission_path.read_text()

        # Wipe the IR and synthesise a second time from the same fixtures.
        emission_path.unlink()
        second = synthesize_fixtures_emission_from_existing(package_dir)
        second_text = emission_path.read_text()

        assert first == second
        assert first_text == second_text

    def test_log_message_on_synthesis(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        """Synthesizer logs an unambiguous fallback-path message."""
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="alpha",
            description="alpha desc",
            inputs={"x": 1},
        )
        configure_logger()

        with caplog.at_level(logging.WARNING):
            synthesize_fixtures_emission_from_existing(package_dir)

        joined = "\n".join(rec.message for rec in caplog.records)
        assert "Synthesized fixtures_emission.json" in joined
        assert "fallback" in joined.lower()

    def test_passthrough_when_present_and_unreadable(self, tmp_path: Path) -> None:
        """If the on-disk IR exists but is unreadable JSON, return None so the
        writer-renderer's error path surfaces the corruption."""
        package_dir = tmp_path / "demo_mellea"
        intermediate = package_dir / "intermediate"
        intermediate.mkdir(parents=True)
        (intermediate / "fixtures_emission.json").write_text("not-json{")

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is None

    def test_preserves_coverage_doc(self, tmp_path: Path) -> None:
        """If the existing `__init__.py` carries a real coverage doc, the
        synthesized IR must echo it back so the writer's re-render is faithful.
        """
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="alpha",
            description="alpha desc",
            inputs={"x": 1},
        )
        coverage = "Fixture coverage:\n  C1 Identity: all fixtures\n  C6 Tools: alpha"
        _write_init_file(fixtures_dir, ["alpha"], coverage_doc=coverage)

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is not None
        assert result.get("coverage_doc", "").strip() == coverage.strip()

    def test_skips_auto_generated_placeholder_coverage_doc(self, tmp_path: Path) -> None:
        """The writer's default placeholder docstring must NOT round-trip as
        a real coverage_doc — that would confuse downstream readers and the
        next render would double-wrap it.
        """
        package_dir = tmp_path / "demo_mellea"
        fixtures_dir = package_dir / "fixtures"
        _write_fixture_file(
            fixtures_dir,
            fid="alpha",
            description="alpha desc",
            inputs={"x": 1},
        )
        # No coverage_doc → _write_init_file emits the auto-generated placeholder.
        _write_init_file(fixtures_dir, ["alpha"])

        result = synthesize_fixtures_emission_from_existing(package_dir)

        assert result is not None
        assert "coverage_doc" not in result
